name: Deploy to WordPress Site

on:
  push:
    branches: 
      - main  # Se activa cuando hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'tu_usuario_ftp'
        server: 'fismetbiomedica.com'
        port: 22  # Puerto SSH estándar
        local_path: './'  # Todos los archivos del repositorio
        remote_path: '/public_html/'  # Ruta en tu servidor
        sftp_password: ${{ secrets.FTP_PASSWORD }}